spring:
  application:
    name: panda_dubbo_springboot_consumer
dubbo:
  registry:
    address: zookeeper://192.168.219.134:2181?backup=192.168.219.135:2181,192.168.219.136:2181,192.168.219.137:2181,192.168.219.138:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
service:
  system:
    version: 4.4.4
  login:
    version: 8.8.8
  order:
    version: 6.6.6
  user:
    version: 2.2.2